### ISSUE TITLE
ft_atoi_base condition should exclude max_digit

### ISSUE THREAD

**Issue by adshz** [pasqualerossi/42-School-Exam-Rank-02#67]
```
  8 int get_digit(char c, int digits_in_base)
  9 {
 10         int max_digit;
 11         if (digits_in_base <= 10)
 12                 max_digit = digits_in_base + '0';
 13         else
 14                 max_digit = digits_in_base - 10 + 'a';
 15         if (c >= '0' && c <= '9' && c <= max_digit)
 16                 return (c - '0');
 17         else if (c >= 'a' && c <= 'f' && c <= max_digit)
 18                 return (10 + c - 'a');
 19         else
 20                 return (-1);
 21 }
```

In the line 15 and line 17, the condition is wrong. In any base $b$, the digits must be in the range of 0 to $b-1$. For example, the valid digits are 0 and 1 if we are talking about base 2. So the condition should exceed the maximum allowable digits.

**Comment by pasqualerossi** [comment]
create a pull request and I'll accept the request.

**Comment by C42joseri** [comment]
Had the same kind of problem with 'f' being accepted in base 15. 
In theory we should only be able to go up to 'e' (being 14 in base 10). The code does 'e' and '10' correctly, showing 14 and 15 respectively, the problem is, it also shows 15 for 'f'.
When going through the code at first, I noticed something strange with base 16.  The 'else if' condition in line 17 excluded 'g' as a character although the 'c <= max_digit' would have included it. 
Everything else seems  OKAY! I'm still fairly new to 42 and coding in general so please bear with me ^^
Also, thank you for your github! I don't know what I'd do with out it . You're a REAL G :) :)

**Comment by pasqualerossi** [comment]
create a pull request and I'll update it. Thanks!
